//! `GeoGraphics` — minimal geographic map rendering.
//!
//! Renders a whole-world equirectangular map using the embedded
//! lowest-resolution (1:110m) Natural Earth admin-0 countries data set
//! (see `resources/ne_110m_countries.bin`, generated by
//! `scripts/gen_geo_data.wls` from <https://www.naturalearthdata.com>).
//!
//! Supported geo primitives inside the content list:
//!   * `GeoMarker[pos]` / `GeoMarker[{pos, …}]` — a map pin at each position
//!   * `Point[pos]` / `Point[{pos, …}]`         — a filled dot at each position
//! plus the color directives and `PointSize` understood by ordinary Graphics.
//!
//! A position is `GeoPosition[{lat, lon}]`, `GeoPosition[{lat, lon, h}]` or a
//! bare `{lat, lon}` pair (latitude first, matching the Wolfram Language).
//!
//! The view auto-zooms to fit the data: a single point gets a square regional
//! window, several points are framed with padding, and a map with no data shows
//! the whole globe. The image height follows the data aspect ratio so the map
//! is never distorted. `ImageSize` (width) and `GeoRange` (`"World"`, `All`, or
//! an explicit `{{latmin, latmax}, {lonmin, lonmax}}` window) are honored.

use crate::InterpreterError;
use crate::functions::graphics::{Color, expr_to_f64, parse_color};
use crate::syntax::Expr;
use std::collections::HashMap;
use std::sync::OnceLock;

/// Embedded Natural Earth 1:110m countries blob. See module docs / generator.
static COUNTRIES_BIN: &[u8] =
  include_bytes!("../../resources/ne_110m_countries.bin");

/// A polygon is a list of rings; each ring is a list of (lon, lat) degrees.
type Ring = Vec<(f32, f32)>;
type Polygon = Vec<Ring>;

fn read_u32(buf: &[u8], i: &mut usize) -> u32 {
  let v = u32::from_le_bytes([buf[*i], buf[*i + 1], buf[*i + 2], buf[*i + 3]]);
  *i += 4;
  v
}

fn read_u16(buf: &[u8], i: &mut usize) -> u16 {
  let v = u16::from_le_bytes([buf[*i], buf[*i + 1]]);
  *i += 2;
  v
}

fn read_i16(buf: &[u8], i: &mut usize) -> i16 {
  let v = i16::from_le_bytes([buf[*i], buf[*i + 1]]);
  *i += 2;
  v
}

/// One country: its Natural Earth `NAME` and its polygons.
pub struct Country {
  pub name: String,
  pub polygons: Vec<Polygon>,
}

fn read_polygons(buf: &[u8], i: &mut usize) -> Vec<Polygon> {
  let num_polys = read_u16(buf, i) as usize;
  let mut polys = Vec::with_capacity(num_polys);
  for _ in 0..num_polys {
    let num_rings = read_u16(buf, i) as usize;
    let mut rings = Vec::with_capacity(num_rings);
    for _ in 0..num_rings {
      let n = read_u16(buf, i) as usize;
      let mut ring = Vec::with_capacity(n);
      for _ in 0..n {
        let lon = read_i16(buf, i) as f32 / 100.0;
        let lat = read_i16(buf, i) as f32 / 100.0;
        ring.push((lon, lat));
      }
      rings.push(ring);
    }
    polys.push(rings);
  }
  polys
}

fn decode_countries(buf: &[u8]) -> Vec<Country> {
  let mut i = 0usize;
  let num = read_u32(buf, &mut i) as usize;
  let mut countries = Vec::with_capacity(num);
  for _ in 0..num {
    let name_len = read_u16(buf, &mut i) as usize;
    let name = String::from_utf8_lossy(&buf[i..i + name_len]).into_owned();
    i += name_len;
    let polygons = read_polygons(buf, &mut i);
    countries.push(Country { name, polygons });
  }
  countries
}

/// All countries with their names and geometry (decoded once).
pub fn world_countries() -> &'static Vec<Country> {
  static CACHE: OnceLock<Vec<Country>> = OnceLock::new();
  CACHE.get_or_init(|| decode_countries(COUNTRIES_BIN))
}

/// Every polygon on the map, flattened in country order (for the basemap).
fn world_polygons() -> impl Iterator<Item = &'static Polygon> {
  world_countries().iter().flat_map(|c| c.polygons.iter())
}

/// Natural Earth uses abbreviated names for a few countries; map them to a form
/// that `country_data`'s resolver recognizes so they can still be looked up.
fn fixup_ne_name(ne: &str) -> &str {
  match ne {
    "Dem. Rep. Congo" => "Democratic Republic of the Congo",
    "Central African Rep." => "Central African Republic",
    "Dominican Rep." => "Dominican Republic",
    "Eq. Guinea" => "Equatorial Guinea",
    "S. Sudan" => "South Sudan",
    "Bosnia and Herz." => "Bosnia and Herzegovina",
    "Solomon Is." => "Solomon Islands",
    "W. Sahara" => "Western Sahara",
    other => other,
  }
}

/// Find the polygons of the country whose name resolves (via `country_data`) to
/// the same canonical country as `query`. Returns `None` for unknown names or
/// non-sovereign territories not in the knowledge base.
pub fn country_polygons(query: &str) -> Option<&'static [Polygon]> {
  let canon = crate::functions::country_data::canonical_name(query)?;
  world_countries().iter().find_map(|c| {
    let ne_canon =
      crate::functions::country_data::canonical_name(fixup_ne_name(&c.name))?;
    (ne_canon == canon).then_some(c.polygons.as_slice())
  })
}

// ── Cartographic colors (light "Default"-style basemap) ───────────────────

const OCEAN_FILL: &str = "rgb(214,232,245)";
const LAND_FILL: &str = "rgb(245,242,233)";
const BORDER_STROKE: &str = "rgb(176,169,159)";

// ── Position extraction ───────────────────────────────────────────────────

/// Lowercased country-name → code index, replicating keshvar's `find_by_name`:
/// it maps each country's official ISO short and long names plus every
/// translated/unofficial name to that country. We build it ourselves from the
/// `translations` data instead of enabling keshvar's `search-translations`
/// feature, whose single auto-generated ~34k-entry `HashMap` literal adds ~20s
/// to every clean compile. The result is byte-for-byte identical to
/// `find_by_name` over the whole name set (verified against all ~33k keys).
fn country_name_index() -> &'static HashMap<String, keshvar::Alpha2> {
  static INDEX: OnceLock<HashMap<String, keshvar::Alpha2>> = OnceLock::new();
  INDEX.get_or_init(|| {
    let mut m = HashMap::new();
    for c in keshvar::CountryIterator::new() {
      m.insert(c.iso_short_name().to_lowercase(), c.alpha2());
      m.insert(c.iso_long_name().to_lowercase(), c.alpha2());
      for v in c.translations().values() {
        m.insert(v.to_lowercase(), c.alpha2());
      }
    }
    m
  })
}

/// Look up a country by (English/translated) name, matched case-insensitively
/// via [`country_name_index`].
///
/// Materializing a country's data (including subdivisions) uses a single deep
/// stack frame that overruns a small thread stack, so we run the lookup — which
/// builds the index on first call and reifies the matched `Country` — behind
/// `stacker::maybe_grow` to borrow a large temporary stack when needed.
fn keshvar_country(name: &str) -> Option<keshvar::Country> {
  let lower = name.to_lowercase();
  stacker::maybe_grow(4 * 1024 * 1024, 16 * 1024 * 1024, || {
    country_name_index().get(&lower).map(|a| a.to_country())
  })
}

/// The geographic center `(lat, lon)` of a country.
fn country_centroid(name: &str) -> Option<(f64, f64)> {
  let g = keshvar_country(name)?.geo();
  Some((g.latitude(), g.longitude()))
}

/// The center `(lat, lon)` of a `country`'s administrative subdivision named
/// `region`, matched case-insensitively against the subdivision's local name,
/// any of its translated names, or its ISO 3166-2 code (so `"Bavaria"`,
/// `"Bayern"`, and `"BY"` all find the same German state).
fn subdivision_centroid_in(
  country: &keshvar::Country,
  region: &str,
) -> Option<(f64, f64)> {
  for (code, s) in country.subdivisions().iter() {
    let hit = code.eq_ignore_ascii_case(region)
      || s.name().eq_ignore_ascii_case(region)
      || s
        .translations()
        .values()
        .any(|t| t.eq_ignore_ascii_case(region));
    if hit
      && let Some(g) = s.geo()
      && let (Some(lat), Some(lon)) = (g.latitude(), g.longitude())
    {
      return Some((lat, lon));
    }
  }
  None
}

/// Resolve a geographic `Entity[…]` specification to a `(lat, lon)` using the
/// keshvar gazetteer.
///
///   * `Entity["Country", "Germany"]`            → the country's center
///   * `Entity["City", {city, region, country}]` → the subdivision's center
///   * `Entity["AdministrativeDivision", {region, country}]` → ditto
///
/// keshvar has no city-level coordinates, so a city falls back to the center of
/// its administrative subdivision (the `region`), and that in turn falls back to
/// the country's center if the region can't be matched.
fn entity_to_latlon(expr: &Expr) -> Option<(f64, f64)> {
  let Expr::FunctionCall { name, args } = expr else {
    return None;
  };
  if name != "Entity" || args.len() != 2 {
    return None;
  }
  let Expr::String(kind) = &args[0] else {
    return None;
  };
  match kind.as_str() {
    "Country" => match &args[1] {
      Expr::String(name) => country_centroid(name),
      _ => None,
    },
    "City" | "AdministrativeDivision" => {
      let Expr::List(parts) = &args[1] else {
        return None;
      };
      let strs: Vec<&str> = parts
        .iter()
        .filter_map(|p| match p {
          Expr::String(s) => Some(s.as_str()),
          _ => None,
        })
        .collect();
      // The country is the last element; the region (if any) is the one before.
      let country = keshvar_country(strs.last()?)?;
      let region = strs.len().checked_sub(2).map(|i| strs[i]);
      region
        .and_then(|r| subdivision_centroid_in(&country, r))
        .or_else(|| {
          let g = country.geo();
          Some((g.latitude(), g.longitude()))
        })
    }
    _ => None,
  }
}

/// Extract `(lat, lon)` from a geographic `Entity[…]`, `GeoPosition[{lat, lon[,
/// h]}]`, or a bare `{lat, lon[, h]}` list.
pub fn position_to_latlon(expr: &Expr) -> Option<(f64, f64)> {
  if let Some(p) = entity_to_latlon(expr) {
    return Some(p);
  }
  let coords = match expr {
    Expr::FunctionCall { name, args }
      if name == "GeoPosition" && args.len() == 1 =>
    {
      &args[0]
    }
    other => other,
  };
  if let Expr::List(items) = coords
    && items.len() >= 2
  {
    let lat = expr_to_f64(&items[0])?;
    let lon = expr_to_f64(&items[1])?;
    return Some((lat, lon));
  }
  None
}

/// Extract one or more positions from a `GeoMarker`/`Point` argument, which may
/// be a single position or a list of positions.
pub fn positions_from_arg(expr: &Expr) -> Vec<(f64, f64)> {
  // Single position forms first.
  if let Some(p) = position_to_latlon(expr) {
    return vec![p];
  }
  // GeoPosition[{{lat,lon},{lat,lon},…}] or a bare list of positions.
  let list = match expr {
    Expr::FunctionCall { name, args }
      if name == "GeoPosition" && args.len() == 1 =>
    {
      &args[0]
    }
    other => other,
  };
  if let Expr::List(items) = list {
    let mut out = Vec::new();
    for it in items.iter() {
      if let Some(p) = position_to_latlon(it) {
        out.push(p);
      }
    }
    return out;
  }
  Vec::new()
}

// ── Projection / view window ──────────────────────────────────────────────

/// Meters per degree of latitude (mean, spherical Earth).
const M_PER_DEG_LAT: f64 = 111_320.0;

/// Padding added on each side of the data bounding box (fraction of span).
const RANGE_PADDING: f64 = 0.15;
/// Minimum half-span (in latitude degrees) when fitting two or more points,
/// so nearly-coincident points don't zoom past the basemap's resolution.
const MIN_HALFSPAN_LAT: f64 = 5.0;
/// Half-span (in latitude degrees) used for a single data point, giving it some
/// regional context.
const SINGLE_HALFSPAN_LAT: f64 = 12.0;

/// The map projection (the `GeoProjection` option).
#[derive(Clone, Copy, PartialEq)]
enum Projection {
  /// Equidistant cylindrical with a standard parallel at the view center
  /// (longitudes scaled by `cos(lat_c)`); the Woxi default.
  EquidistantCylindrical,
  /// Web/spherical Mercator — conformal, the Wolfram default.
  Mercator,
}

fn parse_projection(expr: &Expr) -> Option<Projection> {
  let s = match expr {
    Expr::String(s) | Expr::Identifier(s) => s.as_str(),
    _ => return None,
  };
  match s {
    "Mercator" => Some(Projection::Mercator),
    "Equirectangular" | "EquidistantCylindrical" => {
      Some(Projection::EquidistantCylindrical)
    }
    _ => None,
  }
}

/// Mercator northing for a latitude (degrees), clamped away from the poles.
fn mercator_y(lat_deg: f64) -> f64 {
  let lat = lat_deg.clamp(-85.05, 85.05).to_radians();
  (std::f64::consts::FRAC_PI_4 + lat / 2.0).tan().ln()
}

/// A projection ready to map (lon, lat) degrees to SVG pixel coordinates. The
/// projection-specific parameters are baked in by [`build_view`].
struct GeoView {
  w: f64,
  h: f64,
  projection: Projection,
  /// Top-left reference: minimum longitude and the projected y at the top edge.
  ref_lon: f64,
  ref_y: f64,
  /// Pixels per projected x-unit and y-unit (degrees, or radians for Mercator).
  sx: f64,
  sy: f64,
}

impl GeoView {
  /// Project (lon, lat) in degrees to SVG pixel coordinates.
  fn project(&self, lon: f64, lat: f64) -> (f64, f64) {
    let px = (lon - self.ref_lon) * self.sx;
    let py = match self.projection {
      Projection::EquidistantCylindrical => (self.ref_y - lat) * self.sy,
      Projection::Mercator => (self.ref_y - mercator_y(lat)) * self.sy,
    };
    (px, py)
  }
}

/// Requested geographic range (the `GeoRange` option).
enum GeoRange {
  /// Fit the data automatically (the default).
  Auto,
  /// The whole globe.
  World,
  /// A disk of the given radius (meters) around the data center.
  Radius(f64),
  /// An explicit `{{latmin, latmax}, {lonmin, lonmax}}` window.
  Explicit {
    lat0: f64,
    lat1: f64,
    lon0: f64,
    lon1: f64,
  },
}

fn parse_geo_range(expr: &Expr) -> Option<GeoRange> {
  match expr {
    Expr::String(s) | Expr::Identifier(s) => match s.as_str() {
      "World" => Some(GeoRange::World),
      "All" | "Automatic" => Some(GeoRange::Auto),
      _ => None,
    },
    // GeoRange -> Quantity[r, unit]: a disk of radius r around the data.
    Expr::FunctionCall { name, .. } if name == "Quantity" => {
      radius_to_meters(expr).map(GeoRange::Radius)
    }
    Expr::List(items) if items.len() == 2 => {
      if let (Expr::List(la), Expr::List(lo)) = (&items[0], &items[1])
        && la.len() == 2
        && lo.len() == 2
      {
        Some(GeoRange::Explicit {
          lat0: expr_to_f64(&la[0])?,
          lat1: expr_to_f64(&la[1])?,
          lon0: expr_to_f64(&lo[0])?,
          lon1: expr_to_f64(&lo[1])?,
        })
      } else {
        None
      }
    }
    _ => None,
  }
}

/// cos of a latitude, clamped so near-polar views don't blow up the x-scale.
fn lon_scale(lat_deg: f64) -> f64 {
  (lat_deg.clamp(-80.0, 80.0)).to_radians().cos().max(0.17)
}

/// Compute the view center and half-spans (in degrees) from the data positions
/// and the requested `GeoRange`. Returns `(lon_c, lat_c, half_lon, half_lat)`.
fn compute_window(
  positions: &[(f64, f64)],
  range: &GeoRange,
) -> (f64, f64, f64, f64) {
  match range {
    GeoRange::World => (0.0, 0.0, 180.0, 90.0),
    GeoRange::Radius(meters) => {
      if positions.is_empty() {
        return (0.0, 0.0, 180.0, 90.0);
      }
      // Center on the data's bounding-box center, then span ±radius each way.
      let lat_min = positions.iter().map(|p| p.0).fold(f64::INFINITY, f64::min);
      let lat_max = positions
        .iter()
        .map(|p| p.0)
        .fold(f64::NEG_INFINITY, f64::max);
      let lon_min = positions.iter().map(|p| p.1).fold(f64::INFINITY, f64::min);
      let lon_max = positions
        .iter()
        .map(|p| p.1)
        .fold(f64::NEG_INFINITY, f64::max);
      let lat_c = (lat_min + lat_max) / 2.0;
      let lon_c = (lon_min + lon_max) / 2.0;
      let half_lat = meters / M_PER_DEG_LAT;
      let half_lon = half_lat / lon_scale(lat_c);
      (lon_c, lat_c, half_lon, half_lat)
    }
    GeoRange::Explicit {
      lat0,
      lat1,
      lon0,
      lon1,
    } => (
      (lon0 + lon1) / 2.0,
      (lat0 + lat1) / 2.0,
      (lon1 - lon0).abs() / 2.0,
      (lat1 - lat0).abs() / 2.0,
    ),
    GeoRange::Auto => {
      if positions.is_empty() {
        return (0.0, 0.0, 180.0, 90.0);
      }
      let lat_min = positions.iter().map(|p| p.0).fold(f64::INFINITY, f64::min);
      let lat_max = positions
        .iter()
        .map(|p| p.0)
        .fold(f64::NEG_INFINITY, f64::max);
      let lon_min = positions.iter().map(|p| p.1).fold(f64::INFINITY, f64::min);
      let lon_max = positions
        .iter()
        .map(|p| p.1)
        .fold(f64::NEG_INFINITY, f64::max);
      let lat_c = (lat_min + lat_max) / 2.0;
      let lon_c = (lon_min + lon_max) / 2.0;
      let k = lon_scale(lat_c);

      let span_lat = lat_max - lat_min;
      let span_lon = lon_max - lon_min;
      if span_lat <= 0.0 && span_lon <= 0.0 {
        // Single point (or all coincident): a square regional window.
        return (lon_c, lat_c, SINGLE_HALFSPAN_LAT / k, SINGLE_HALFSPAN_LAT);
      }
      // Fit the bounding box, enforce a minimum span, then pad.
      let mut half_lat = (span_lat / 2.0).max(MIN_HALFSPAN_LAT);
      let mut half_lon = (span_lon / 2.0).max(MIN_HALFSPAN_LAT / k);
      half_lat *= 1.0 + RANGE_PADDING;
      half_lon *= 1.0 + RANGE_PADDING;
      (lon_c, lat_c, half_lon, half_lat)
    }
  }
}

/// Build the projection for the given data, image width and requested range.
/// The image height is derived from the (projected) data aspect ratio so the
/// map is never distorted.
fn build_view(
  positions: &[(f64, f64)],
  width: f64,
  range: &GeoRange,
  projection: Projection,
) -> GeoView {
  let (lon_c, lat_c, half_lon, half_lat) = compute_window(positions, range);
  let half_lon = half_lon.max(1e-6);
  let half_lat = half_lat.max(1e-6);
  let lon_span = 2.0 * half_lon;
  let ref_lon = lon_c - half_lon;
  // Longitude always maps linearly across the full width.
  let sx = width / lon_span;
  let (sy, ref_y, height) = match projection {
    Projection::EquidistantCylindrical => {
      // Latitude is undistorted; cos(lat_c) sets the vertical scale so a
      // degree of longitude near the center matches a degree of latitude.
      let k = lon_scale(lat_c);
      let sy = sx / k;
      (sy, lat_c + half_lat, 2.0 * half_lat * sy)
    }
    Projection::Mercator => {
      // Conformal: equal pixels-per-radian in x and y.
      let sy = sx * 180.0 / std::f64::consts::PI;
      let y_top = mercator_y(lat_c + half_lat);
      let y_bot = mercator_y(lat_c - half_lat);
      (sy, y_top, (y_top - y_bot) * sy)
    }
  };
  GeoView {
    w: width,
    h: height.round().max(1.0),
    projection,
    ref_lon,
    ref_y,
    sx,
    sy,
  }
}

// ── Marker rendering ──────────────────────────────────────────────────────

/// Append a teardrop map pin whose tip points at (px, py).
fn render_pin(svg: &mut String, px: f64, py: f64, color: &Color, scale: f64) {
  let r = 4.0 * scale;
  let d = 14.0 * scale; // tip-to-bulb-center distance
  let cy = py - d; // bulb center
  // Tangent points from the tip onto the bulb circle.
  let cos_t = (r / d).clamp(-1.0, 1.0);
  let sin_t = (1.0 - cos_t * cos_t).sqrt();
  let lx = px - r * sin_t;
  let rx = px + r * sin_t;
  let ty = cy + r * cos_t;
  let fill = color.to_svg_rgb();
  svg.push_str(&format!(
    "<path d=\"M {px:.1} {py:.1} L {rx:.1} {ty:.1} A {r:.1} {r:.1} 0 1 0 {lx:.1} {ty:.1} Z\" \
     fill=\"{fill}\" stroke=\"rgb(60,60,60)\" stroke-width=\"0.8\"/>\n"
  ));
  // White hole in the bulb.
  svg.push_str(&format!(
    "<circle cx=\"{px:.1}\" cy=\"{cy:.1}\" r=\"{:.1}\" fill=\"white\"/>\n",
    r * 0.45
  ));
}

/// Append a filled dot at (px, py).
fn render_dot(svg: &mut String, px: f64, py: f64, color: &Color, radius: f64) {
  svg.push_str(&format!(
    "<circle cx=\"{px:.1}\" cy=\"{py:.1}\" r=\"{radius:.1}\" fill=\"{}\"/>\n",
    color.to_svg_rgb()
  ));
}

/// Inverse Gudermannian: latitude (degrees) for a Mercator northing.
fn inverse_mercator_y(y: f64) -> f64 {
  y.sinh().atan().to_degrees()
}

impl GeoView {
  /// Geographic bounds `(lat_min, lat_max, lon_min, lon_max)` of the view.
  fn bounds(&self) -> (f64, f64, f64, f64) {
    let lon_min = self.ref_lon;
    let lon_max = self.ref_lon + self.w / self.sx;
    let (lat_top, lat_bot) = match self.projection {
      Projection::EquidistantCylindrical => {
        (self.ref_y, self.ref_y - self.h / self.sy)
      }
      Projection::Mercator => (
        inverse_mercator_y(self.ref_y),
        inverse_mercator_y(self.ref_y - self.h / self.sy),
      ),
    };
    (lat_bot, lat_top, lon_min, lon_max)
  }
}

/// A "nice" grid spacing (degrees) giving roughly 4–10 lines across `span`.
fn nice_grid_step(span: f64) -> f64 {
  const STEPS: [f64; 9] = [1.0, 2.0, 5.0, 10.0, 15.0, 20.0, 30.0, 45.0, 90.0];
  let target = span / 6.0;
  *STEPS
    .iter()
    .find(|&&s| s >= target)
    .unwrap_or(STEPS.last().unwrap())
}

const GRID_STROKE: &str = "rgb(170,190,205)";

/// Draw latitude/longitude graticule lines clipped to the view. Both supported
/// projections are cylindrical, so grid lines are straight.
fn render_graticule(svg: &mut String, proj: &GeoView) {
  let (lat_min, lat_max, lon_min, lon_max) = proj.bounds();
  let lat_step = nice_grid_step(lat_max - lat_min);
  let lon_step = nice_grid_step(lon_max - lon_min);
  let line = |svg: &mut String, x1: f64, y1: f64, x2: f64, y2: f64| {
    svg.push_str(&format!(
      "<line x1=\"{x1:.1}\" y1=\"{y1:.1}\" x2=\"{x2:.1}\" y2=\"{y2:.1}\" \
       stroke=\"{GRID_STROKE}\" stroke-width=\"0.5\"/>\n"
    ));
  };
  // Parallels (constant latitude).
  let mut lat = (lat_min / lat_step).ceil() * lat_step;
  while lat <= lat_max + 1e-9 {
    let (_, y) = proj.project(lon_min, lat);
    let (x2, _) = proj.project(lon_max, lat);
    line(svg, 0.0, y, x2, y);
    lat += lat_step;
  }
  // Meridians (constant longitude).
  let mut lon = (lon_min / lon_step).ceil() * lon_step;
  while lon <= lon_max + 1e-9 {
    let (x, _) = proj.project(lon, lat_max);
    let (_, y2) = proj.project(lon, lat_min);
    line(svg, x, 0.0, x, y2);
    lon += lon_step;
  }
}

/// The country name of an `Entity["Country", name]` (or `None`).
fn entity_country_name(expr: &Expr) -> Option<&str> {
  if let Expr::FunctionCall { name, args } = expr
    && name == "Entity"
    && args.len() == 2
    && let (Expr::String(kind), Expr::String(country)) = (&args[0], &args[1])
    && kind == "Country"
  {
    return Some(country);
  }
  None
}

/// Bounding box `(lat_min, lat_max, lon_min, lon_max)` of a country's polygons.
fn polygons_bbox(polys: &[Polygon]) -> Option<(f64, f64, f64, f64)> {
  let mut b: Option<(f64, f64, f64, f64)> = None;
  for ring in polys.iter().flatten() {
    for &(lon, lat) in ring {
      let (lon, lat) = (lon as f64, lat as f64);
      b = Some(match b {
        None => (lat, lat, lon, lon),
        Some((la0, la1, lo0, lo1)) => {
          (la0.min(lat), la1.max(lat), lo0.min(lon), lo1.max(lon))
        }
      });
    }
  }
  b
}

/// Fill a country's polygons (even-odd handles enclaves/holes) with `color`.
fn render_country(
  svg: &mut String,
  polys: &[Polygon],
  proj: &GeoView,
  color: &Color,
) {
  let mut d = String::new();
  for ring in polys.iter().flatten() {
    for (k, (lon, lat)) in ring.iter().enumerate() {
      let (x, y) = proj.project(*lon as f64, *lat as f64);
      d.push_str(&format!(
        "{} {x:.1} {y:.1} ",
        if k == 0 { "M" } else { "L" }
      ));
    }
    d.push_str("Z ");
  }
  if d.is_empty() {
    return;
  }
  let c = color.to_svg_rgb();
  svg.push_str(&format!(
    "<path d=\"{d}\" fill=\"{c}\" fill-rule=\"evenodd\" fill-opacity=\"0.65\" \
     stroke=\"{c}\" stroke-width=\"0.6\"/>\n"
  ));
}

/// Sample a geodesic circle of radius `radius_m` meters around `(lat, lon)` as
/// a closed list of boundary points, used by `GeoCircle` / `GeoDisk`.
fn geo_circle_points(
  lat: f64,
  lon: f64,
  radius_m: f64,
  segments: usize,
) -> Vec<(f64, f64)> {
  (0..segments)
    .map(|i| {
      let az = 360.0 * i as f64 / segments as f64;
      crate::functions::geo_math::destination(lat, lon, az, radius_m)
    })
    .collect()
}

/// Append an SVG polyline/polygon path for a sequence of projected positions.
fn render_geo_path(
  svg: &mut String,
  pts: &[(f64, f64)],
  proj: &GeoView,
  color: &Color,
  closed: bool,
  filled: bool,
) {
  if pts.len() < 2 {
    return;
  }
  let mut d = String::new();
  for (i, (lat, lon)) in pts.iter().enumerate() {
    let (x, y) = proj.project(*lon, *lat);
    d.push_str(&format!(
      "{} {x:.1} {y:.1} ",
      if i == 0 { "M" } else { "L" }
    ));
  }
  if closed {
    d.push('Z');
  }
  let stroke = color.to_svg_rgb();
  let (fill, fill_op) = if filled {
    (stroke.clone(), " fill-opacity=\"0.3\"")
  } else {
    ("none".to_string(), "")
  };
  svg.push_str(&format!(
    "<path d=\"{d}\" fill=\"{fill}\"{fill_op} stroke=\"{stroke}\" \
     stroke-width=\"1.5\" stroke-linejoin=\"round\"/>\n"
  ));
}

/// Append a filled `GeoHistogram` bin tile: a closed polygon in the bin's
/// density color with a thin white seam between adjacent tiles.
fn render_histogram_bin(
  svg: &mut String,
  pts: &[(f64, f64)],
  proj: &GeoView,
  color: &Color,
) {
  if pts.len() < 3 {
    return;
  }
  let mut d = String::new();
  for (i, (lat, lon)) in pts.iter().enumerate() {
    let (x, y) = proj.project(*lon, *lat);
    d.push_str(&format!(
      "{} {x:.1} {y:.1} ",
      if i == 0 { "M" } else { "L" }
    ));
  }
  d.push('Z');
  svg.push_str(&format!(
    "<path d=\"{d}\" fill=\"{}\" fill-opacity=\"0.7\" stroke=\"white\" \
     stroke-width=\"0.5\"/>\n",
    color.to_svg_rgb()
  ));
}

// ── PointSize handling ────────────────────────────────────────────────────

/// Pixel radius for a dot given the current `PointSize` directive and image
/// width. Named sizes follow the usual Graphics conventions; numeric values are
/// fractions of the image width.
fn point_radius(point_size: &Option<Expr>, width: f64) -> f64 {
  match point_size {
    None => 3.0,
    Some(Expr::Identifier(s)) => match s.as_str() {
      "Tiny" => 1.5,
      "Small" => 2.5,
      "Medium" => 4.0,
      "Large" => 6.0,
      _ => 3.0,
    },
    Some(e) => match expr_to_f64(e) {
      Some(frac) if frac > 0.0 => (frac * width).max(1.0),
      _ => 3.0,
    },
  }
}

/// Pin scale factor for the current `PointSize` directive (the pin keeps a
/// recognizable shape, so `PointSize` only nudges its overall size).
fn pin_scale(point_size: &Option<Expr>) -> f64 {
  match point_size {
    Some(Expr::Identifier(s)) => match s.as_str() {
      "Tiny" => 0.7,
      "Small" => 0.85,
      "Large" => 1.25,
      _ => 1.0,
    },
    _ => 1.0,
  }
}

// ── Content walking ───────────────────────────────────────────────────────

struct GeoStyle {
  color: Color,
  point_size: Option<Expr>,
}

/// Collect every data position (from `GeoMarker`/`Point`) in the content tree,
/// used to compute the auto-zoom window.
fn collect_positions(expr: &Expr, out: &mut Vec<(f64, f64)>) {
  match expr {
    Expr::List(items) => {
      for it in items.iter() {
        collect_positions(it, out);
      }
    }
    Expr::FunctionCall { name, args } => match name.as_str() {
      "Directive" => {
        for a in args.iter() {
          collect_positions(a, out);
        }
      }
      "GeoMarker"
      | "Point"
      | "GeoPath"
      | "GeoPolygon"
      | "Woxi`GeoHistogramBin"
        if !args.is_empty() =>
      {
        out.extend(positions_from_arg(&args[0]));
      }
      "GeoCircle" | "GeoDisk" if !args.is_empty() => {
        // Frame the circle's center plus a radius ring so it fits in view.
        if let Some((lat, lon)) = position_to_latlon(&args[0]) {
          let radius_m =
            args.get(1).and_then(radius_to_meters).unwrap_or(100_000.0);
          out.extend(geo_circle_points(lat, lon, radius_m, 16));
        }
      }
      "Entity" => {
        // Frame a country to its bounding box.
        if let Some(name) = entity_country_name(expr)
          && let Some(polys) = country_polygons(name)
          && let Some((la0, la1, lo0, lo1)) = polygons_bbox(polys)
        {
          out.push((la0, lo0));
          out.push((la1, lo1));
        }
      }
      _ => {}
    },
    _ => {}
  }
}

/// Interpret a `GeoCircle`/`GeoDisk` radius argument as meters. Accepts a bare
/// number (meters) or `Quantity[r, unit]` for length units.
fn radius_to_meters(expr: &Expr) -> Option<f64> {
  if let Some(m) = expr_to_f64(expr) {
    return Some(m);
  }
  if let Expr::FunctionCall { name, args } = expr
    && name == "Quantity"
    && args.len() == 2
    && let Some(v) = expr_to_f64(&args[0])
    && let Expr::String(unit) = &args[1]
  {
    let factor = match unit.as_str() {
      "Meters" | "Meter" => 1.0,
      "Kilometers" | "Kilometer" => 1000.0,
      "Miles" | "Mile" => 1609.344,
      "Feet" | "Foot" => 0.3048,
      "NauticalMiles" | "NauticalMile" => 1852.0,
      _ => return None,
    };
    return Some(v * factor);
  }
  None
}

/// Walk the content list, tracking color/PointSize directives and emitting SVG
/// for each geo primitive encountered.
fn render_content(
  expr: &Expr,
  style: &mut GeoStyle,
  proj: &GeoView,
  svg: &mut String,
) {
  match expr {
    Expr::List(items) => {
      for it in items.iter() {
        render_content(it, style, proj, svg);
      }
    }
    Expr::FunctionCall { name, args } => match name.as_str() {
      "Directive" => {
        for a in args.iter() {
          render_content(a, style, proj, svg);
        }
      }
      "PointSize" | "AbsolutePointSize" if args.len() == 1 => {
        style.point_size = Some(args[0].clone());
      }
      "GeoMarker" if !args.is_empty() => {
        let scale = pin_scale(&style.point_size);
        for (lat, lon) in positions_from_arg(&args[0]) {
          let (px, py) = proj.project(lon, lat);
          render_pin(svg, px, py, &style.color, scale);
        }
      }
      "GeoPath" if !args.is_empty() => {
        let pts = positions_from_arg(&args[0]);
        render_geo_path(svg, &pts, proj, &style.color, false, false);
      }
      "GeoPolygon" if !args.is_empty() => {
        let pts = positions_from_arg(&args[0]);
        render_geo_path(svg, &pts, proj, &style.color, true, true);
      }
      // Internal primitive emitted by GeoHistogram (the backtick keeps it out
      // of user code): a density bin filled with the current color.
      "Woxi`GeoHistogramBin" if !args.is_empty() => {
        let pts = positions_from_arg(&args[0]);
        render_histogram_bin(svg, &pts, proj, &style.color);
      }
      "GeoCircle" if !args.is_empty() => {
        if let Some((lat, lon)) = position_to_latlon(&args[0]) {
          let radius_m =
            args.get(1).and_then(radius_to_meters).unwrap_or(100_000.0);
          let pts = geo_circle_points(lat, lon, radius_m, 96);
          render_geo_path(svg, &pts, proj, &style.color, true, false);
        }
      }
      "GeoDisk" if !args.is_empty() => {
        if let Some((lat, lon)) = position_to_latlon(&args[0]) {
          let radius_m =
            args.get(1).and_then(radius_to_meters).unwrap_or(100_000.0);
          let pts = geo_circle_points(lat, lon, radius_m, 96);
          render_geo_path(svg, &pts, proj, &style.color, true, true);
        }
      }
      "Entity" => {
        if let Some(name) = entity_country_name(expr)
          && let Some(polys) = country_polygons(name)
        {
          render_country(svg, polys, proj, &style.color);
        }
      }
      "Point" if !args.is_empty() => {
        let radius = point_radius(&style.point_size, proj.w);
        for (lat, lon) in positions_from_arg(&args[0]) {
          let (px, py) = proj.project(lon, lat);
          render_dot(svg, px, py, &style.color, radius);
        }
      }
      _ => {
        // Treat anything color-like as a directive; ignore the rest.
        if let Some(c) = parse_color(expr) {
          style.color = c;
        }
      }
    },
    Expr::Identifier(_) => {
      if let Some(c) = parse_color(expr) {
        style.color = c;
      }
    }
    _ => {}
  }
}

// ── GeoNearest (point-in-country) ─────────────────────────────────────────

/// Ray-casting point-in-polygon over every ring of a country (even-odd rule, so
/// enclaves and holes are handled). `x = lon`, `y = lat`.
fn point_in_country(lat: f64, lon: f64, polys: &[Polygon]) -> bool {
  let mut inside = false;
  for ring in polys.iter().flatten() {
    let n = ring.len();
    if n < 3 {
      continue;
    }
    let mut j = n - 1;
    for i in 0..n {
      let (xi, yi) = (ring[i].0 as f64, ring[i].1 as f64);
      let (xj, yj) = (ring[j].0 as f64, ring[j].1 as f64);
      if (yi > lat) != (yj > lat)
        && lon < (xj - xi) * (lat - yi) / (yj - yi) + xi
      {
        inside = !inside;
      }
      j = i;
    }
  }
  inside
}

/// The canonical `Entity["Country", …]` for a Natural Earth country record,
/// falling back to the raw Natural Earth name for non-sovereign territories.
fn country_entity(c: &Country) -> Expr {
  let name =
    crate::functions::country_data::canonical_name(fixup_ne_name(&c.name))
      .unwrap_or(c.name.as_str());
  Expr::FunctionCall {
    name: "Entity".to_string(),
    args: vec![
      Expr::String("Country".to_string()),
      Expr::String(name.to_string()),
    ]
    .into(),
  }
}

/// `GeoNearest["Country", pos]` — the country containing `pos` (or, for a point
/// in the ocean, the one whose border is nearest). Returns a one-element list,
/// matching the Wolfram Language.
pub fn geo_nearest_ast(args: &[Expr]) -> Result<Expr, InterpreterError> {
  if args.len() >= 2
    && let Expr::String(kind) = &args[0]
    && kind == "Country"
    && let Some((lat, lon)) = position_to_latlon(&args[1])
  {
    // First, containment.
    let hit = world_countries()
      .iter()
      .find(|c| point_in_country(lat, lon, &c.polygons));
    // Otherwise, the country with the nearest boundary vertex.
    let chosen = hit.or_else(|| {
      world_countries().iter().min_by(|a, b| {
        nearest_vertex_dist2(lat, lon, &a.polygons)
          .partial_cmp(&nearest_vertex_dist2(lat, lon, &b.polygons))
          .unwrap_or(std::cmp::Ordering::Equal)
      })
    });
    if let Some(c) = chosen {
      return Ok(Expr::List(vec![country_entity(c)].into()));
    }
  }
  Ok(Expr::FunctionCall {
    name: "GeoNearest".to_string(),
    args: args.to_vec().into(),
  })
}

/// Squared distance (in degrees) from `(lat, lon)` to the nearest boundary
/// vertex of a country — a cheap proxy for ranking ocean points.
fn nearest_vertex_dist2(lat: f64, lon: f64, polys: &[Polygon]) -> f64 {
  polys
    .iter()
    .flatten()
    .flatten()
    .map(|&(plon, plat)| {
      let (dlon, dlat) = (plon as f64 - lon, plat as f64 - lat);
      dlon * dlon + dlat * dlat
    })
    .fold(f64::INFINITY, f64::min)
}

// ── GeoRegionValuePlot (choropleth) ───────────────────────────────────────

/// `GeoRegionValuePlot[{Entity[…] -> value, …}, opts]` — a choropleth shading
/// each country by its value. Returns bare `Graphics` (the Wolfram Language
/// additionally wraps the result in `Legended`).
/// Choropleth color scale `t in [0,1]` → `(r, g, b)`: light cream → deep blue,
/// like the default `GeoRegionValuePlot` scale. Shared by the country fills and
/// the legend bar so they agree.
fn choropleth_color(t: f64) -> (f64, f64, f64) {
  let t = t.clamp(0.0, 1.0);
  (0.95 - 0.80 * t, 0.92 - 0.62 * t, 0.85 - 0.30 * t)
}

/// A continuous color-scale legend drawn to the right of the map.
struct Legend {
  lo: f64,
  hi: f64,
  /// Color scale mapping `t in [0,1]` to `(r, g, b)`; must be the same scale
  /// used to shade the map so the legend and the fills agree.
  color: fn(f64) -> (f64, f64, f64),
}

pub fn geo_region_value_plot_ast(
  args: &[Expr],
) -> Result<Expr, InterpreterError> {
  let content = if args.is_empty() {
    Expr::List(vec![].into())
  } else {
    crate::evaluator::evaluate_expr_to_expr(&args[0])?
  };
  let Expr::List(rules) = &content else {
    return Ok(Expr::FunctionCall {
      name: "GeoRegionValuePlot".to_string(),
      args: args.to_vec().into(),
    });
  };
  // Collect (entity, value) pairs.
  let mut pairs: Vec<(Expr, f64)> = Vec::new();
  for r in rules.iter() {
    if let Expr::Rule {
      pattern,
      replacement,
    } = r
      && entity_country_name(pattern).is_some()
      && let Some(v) = expr_to_f64(replacement)
    {
      pairs.push(((**pattern).clone(), v));
    }
  }
  if pairs.is_empty() {
    return Ok(Expr::FunctionCall {
      name: "GeoRegionValuePlot".to_string(),
      args: args.to_vec().into(),
    });
  }
  let lo = pairs.iter().map(|p| p.1).fold(f64::INFINITY, f64::min);
  let hi = pairs.iter().map(|p| p.1).fold(f64::NEG_INFINITY, f64::max);
  // Build a content list of (color directive, entity) shading by value.
  let mut items: Vec<Expr> = Vec::with_capacity(pairs.len() * 2);
  for (entity, v) in &pairs {
    let t = if hi > lo { (v - lo) / (hi - lo) } else { 0.5 };
    let (r, g, b) = choropleth_color(t);
    items.push(Expr::FunctionCall {
      name: "RGBColor".to_string(),
      args: vec![Expr::Real(r), Expr::Real(g), Expr::Real(b)].into(),
    });
    items.push(entity.clone());
  }
  // Render the shaded map with a color-scale legend on the right.
  let content = Expr::List(items.into());
  geographics_impl(
    &content,
    &args[1..],
    Some(Legend {
      lo,
      hi,
      color: choropleth_color,
    }),
  )
}

// ── GeoHistogram (geographic density histogram) ───────────────────────────

/// √3.
const SQRT3: f64 = 1.732_050_807_568_877_2;

/// Histogram bin color scale `t in [0,1]` → `(r, g, b)`: pale yellow for the
/// sparsest bins to deep red for the densest (darker = denser, following the
/// Wolfram default).
fn heat_color(t: f64) -> (f64, f64, f64) {
  let t = t.clamp(0.0, 1.0);
  (0.98 - 0.43 * t, 0.93 - 0.83 * t, 0.60 - 0.47 * t)
}

/// Tile shape used to bin locations (part of the `bspec` argument).
#[derive(Clone, Copy, PartialEq)]
enum BinShape {
  Hexagon,
  Rectangle,
  Triangle,
}

/// Tile size: a target number of tiles across the data extent, or an explicit
/// tile extent in degrees of latitude (hexagons/triangles use the width as
/// their diameter/side).
enum BinSize {
  Across(f64),
  Degrees(f64, f64),
}

/// How each bin's value is computed from its accumulated weight (`hspec`).
/// With equal-size bins and max-normalized colors, all four shade identically;
/// they differ in the absolute values shown on a `PlotLegends` bar.
#[derive(Clone, Copy, PartialEq)]
enum HeightSpec {
  Count,
  Probability,
  Intensity,
  Pdf,
}

fn parse_bin_shape(s: &str) -> Option<BinShape> {
  match s {
    "Hexagon" => Some(BinShape::Hexagon),
    "Rectangle" => Some(BinShape::Rectangle),
    "Triangle" => Some(BinShape::Triangle),
    _ => None,
  }
}

/// A `Quantity` length as degrees of latitude (`None` for anything else).
fn quantity_to_deg(expr: &Expr) -> Option<f64> {
  if let Expr::FunctionCall { name, .. } = expr
    && name == "Quantity"
  {
    return radius_to_meters(expr).map(|m| m / M_PER_DEG_LAT);
  }
  None
}

/// Parse a `bspec` argument. Returns `(shape, size)` with `None` components
/// meaning "keep the default", or `None` if the expression is not a bin spec.
///
///   * `Automatic`                       — defaults
///   * `n` (positive number)             — about `n` tiles across the data
///   * `"Hexagon" | "Rectangle" | "Triangle"` — tile shape, automatic size
///   * `Quantity[d, unit]`               — tiles of diameter `d`
///   * `{Quantity[w, u], Quantity[h, u]}` — rectangle tiles of width × height
///   * `{shape, n}` / `{shape, Quantity[…]}` — shape with explicit size
fn parse_bin_spec(expr: &Expr) -> Option<(Option<BinShape>, Option<BinSize>)> {
  match expr {
    Expr::Identifier(s) if s == "Automatic" => Some((None, None)),
    Expr::String(s) | Expr::Identifier(s) => {
      parse_bin_shape(s).map(|sh| (Some(sh), None))
    }
    Expr::Integer(_) | Expr::Real(_) => {
      let n = expr_to_f64(expr)?;
      (n > 0.0).then_some((None, Some(BinSize::Across(n))))
    }
    Expr::FunctionCall { name, .. } if name == "Quantity" => {
      let d = quantity_to_deg(expr)?;
      Some((None, Some(BinSize::Degrees(d, d))))
    }
    Expr::List(items) if items.len() == 2 => {
      if let (Some(w), Some(h)) =
        (quantity_to_deg(&items[0]), quantity_to_deg(&items[1]))
      {
        return Some((None, Some(BinSize::Degrees(w, h))));
      }
      let shape = match &items[0] {
        Expr::String(s) | Expr::Identifier(s) => parse_bin_shape(s)?,
        _ => return None,
      };
      let size = if let Some(d) = quantity_to_deg(&items[1]) {
        BinSize::Degrees(d, d)
      } else {
        let n = expr_to_f64(&items[1])?;
        if n <= 0.0 {
          return None;
        }
        BinSize::Across(n)
      };
      Some((Some(shape), Some(size)))
    }
    _ => None,
  }
}

fn parse_height_spec(expr: &Expr) -> Option<HeightSpec> {
  let (Expr::String(s) | Expr::Identifier(s)) = expr else {
    return None;
  };
  match s.as_str() {
    "Count" => Some(HeightSpec::Count),
    "Probability" => Some(HeightSpec::Probability),
    "Intensity" => Some(HeightSpec::Intensity),
    "PDF" => Some(HeightSpec::Pdf),
    _ => None,
  }
}

/// Extract the locations and per-location weights from the data argument: a
/// list of positions (unit weights), an association `pos -> weight`, or
/// `WeightedData[positions, weights]`.
fn histogram_locations(expr: &Expr) -> (Vec<(f64, f64)>, Vec<f64>) {
  match expr {
    Expr::Association(pairs) => {
      let mut pts = Vec::new();
      let mut wts = Vec::new();
      for (k, v) in pairs {
        if let (Some(p), Some(w)) = (position_to_latlon(k), expr_to_f64(v)) {
          pts.push(p);
          wts.push(w);
        }
      }
      (pts, wts)
    }
    // Canonical WeightedData[Automatic, {data, weights}] object (the 2-arg
    // constructor form evaluates to this before we see it).
    Expr::FunctionCall { name, .. } if name == "WeightedData" => {
      let mut pts = Vec::new();
      let mut wts = Vec::new();
      if let Some((data, weights)) =
        crate::evaluator::dispatch::list_operations::weighted_data_parts(expr)
      {
        for (d, w) in data.iter().zip(&weights) {
          if let (Some(p), Some(w)) = (position_to_latlon(d), expr_to_f64(w)) {
            pts.push(p);
            wts.push(w);
          }
        }
      }
      (pts, wts)
    }
    other => {
      let pts = positions_from_arg(other);
      let n = pts.len();
      (pts, vec![1.0; n])
    }
  }
}

/// Round fractional axial hex coordinates to the nearest hex (cube rounding).
fn hex_round(qf: f64, rf: f64) -> (i64, i64) {
  let sf = -qf - rf;
  let mut q = qf.round();
  let mut r = rf.round();
  let s = sf.round();
  let (dq, dr, ds) = ((q - qf).abs(), (r - rf).abs(), (s - sf).abs());
  if dq > dr && dq > ds {
    q = -r - s;
  } else if dr > ds {
    r = -q - s;
  }
  (q as i64, r as i64)
}

/// Bin locations into tiles of the given shape and size. Returns each
/// non-empty bin as its boundary ring (`(lat, lon)` vertices) plus its
/// accumulated weight, in a deterministic (grid-index) order.
///
/// Binning happens in "map units" (`x = lon·cos(lat_c)`, `y = lat`) so tiles
/// are roughly isotropic on the ground, matching the "equal visual size"
/// tiles of the Wolfram Language.
fn compute_geo_bins(
  pts: &[(f64, f64)],
  wts: &[f64],
  shape: BinShape,
  size: &BinSize,
) -> Vec<(Vec<(f64, f64)>, f64)> {
  use std::collections::HashMap;
  let lat_min = pts.iter().map(|p| p.0).fold(f64::INFINITY, f64::min);
  let lat_max = pts.iter().map(|p| p.0).fold(f64::NEG_INFINITY, f64::max);
  let lon_min = pts.iter().map(|p| p.1).fold(f64::INFINITY, f64::min);
  let lon_max = pts.iter().map(|p| p.1).fold(f64::NEG_INFINITY, f64::max);
  let lat_c = (lat_min + lat_max) / 2.0;
  let k = lon_scale(lat_c);
  let x0 = lon_min * k;
  let y0 = lat_min;
  // Tile extent in map degrees. `Across(n)` targets n tiles across the wider
  // side of the data extent; coincident points get a 1° tile for context.
  let (w, h) = match size {
    BinSize::Degrees(w, h) => (*w, *h),
    BinSize::Across(n) => {
      let span = ((lon_max - lon_min) * k).max(lat_max - lat_min);
      let w = if span > 0.0 { span / n } else { 1.0 };
      (w, w)
    }
  };
  let (w, h) = (w.max(1e-9), h.max(1e-9));

  let mut acc: HashMap<(i64, i64), f64> = HashMap::new();
  for (p, wt) in pts.iter().zip(wts) {
    let px = p.1 * k - x0;
    let py = p.0 - y0;
    let key = match shape {
      BinShape::Rectangle => ((px / w).floor() as i64, (py / h).floor() as i64),
      BinShape::Hexagon => {
        // Flat-top hexagons, center-to-vertex radius s = w/2.
        let s = w / 2.0;
        hex_round(2.0 / 3.0 * px / s, (-px / 3.0 + SQRT3 / 3.0 * py) / s)
      }
      BinShape::Triangle => {
        // Equilateral triangles of side w in rows of height w·√3/2; each row
        // is shifted half a side, and triangles alternate up/down. At height
        // `fv` within its row, the up-triangle `m` spans
        // `[m + fv/2, m + 1 - fv/2]` (in row-shifted side units), so a point
        // is in an up triangle exactly when both diagonals `wc ∓ fv/2` fall
        // in the same unit cell. Down triangles get the odd x-keys.
        let th = w * SQRT3 / 2.0;
        let row = (py / th).floor();
        let fv = py / th - row;
        let wc = px / w - row * 0.5;
        let ia = (wc - fv / 2.0).floor() as i64;
        let ib = (wc + fv / 2.0).floor() as i64;
        (if ia == ib { 2 * ia } else { 2 * ia + 1 }, row as i64)
      }
    };
    *acc.entry(key).or_default() += wt;
  }

  // Deterministic output order (HashMap iteration order is random).
  let mut bins: Vec<((i64, i64), f64)> = acc.into_iter().collect();
  bins.sort_by_key(|(key, _)| *key);

  bins
    .into_iter()
    .map(|((ix, iy), v)| {
      let ring: Vec<(f64, f64)> = match shape {
        BinShape::Rectangle => {
          let (xa, ya) = (x0 + ix as f64 * w, y0 + iy as f64 * h);
          vec![
            (ya, xa / k),
            (ya, (xa + w) / k),
            (ya + h, (xa + w) / k),
            (ya + h, xa / k),
          ]
        }
        BinShape::Hexagon => {
          let s = w / 2.0;
          let cx = x0 + s * 1.5 * ix as f64;
          let cy = y0 + s * SQRT3 * (iy as f64 + ix as f64 / 2.0);
          (0..6)
            .map(|i| {
              let a = std::f64::consts::PI / 3.0 * i as f64;
              (cy + s * a.sin(), (cx + s * a.cos()) / k)
            })
            .collect()
        }
        BinShape::Triangle => {
          let th = w * SQRT3 / 2.0;
          let (m, r) = ((ix.div_euclid(2)) as f64, iy as f64);
          let bx = |mm: f64, rr: f64| (x0 + (mm + rr * 0.5) * w) / k;
          let by = |rr: f64| y0 + rr * th;
          if ix.rem_euclid(2) == 0 {
            // Up: base on the row's bottom edge, apex centered above.
            vec![
              (by(r), bx(m, r)),
              (by(r), bx(m + 1.0, r)),
              (by(r + 1.0), bx(m, r + 1.0)),
            ]
          } else {
            // Down: base on the row's top edge, apex centered below.
            vec![
              (by(r), bx(m + 1.0, r)),
              (by(r + 1.0), bx(m + 1.0, r + 1.0)),
              (by(r + 1.0), bx(m, r + 1.0)),
            ]
          }
        }
      };
      (ring, v)
    })
    .collect()
}

/// Signed polygon area (shoelace) of a `(lat, lon)` ring, in square degrees —
/// used by the `"Intensity"`/`"PDF"` height specs.
fn ring_area_deg2(ring: &[(f64, f64)]) -> f64 {
  let n = ring.len();
  let mut a = 0.0;
  for i in 0..n {
    let (y1, x1) = ring[i];
    let (y2, x2) = ring[(i + 1) % n];
    a += x1 * y2 - x2 * y1;
  }
  (a / 2.0).abs()
}

/// `GeoHistogram[locs, bspec?, hspec?, opts…]` — a geographic density
/// histogram: locations are binned into hexagonal (the default), rectangular
/// or triangular tiles of equal visual size, and each non-empty tile is
/// shaded by its value (darker = denser). Weights come from an association
/// `pos -> w` or `WeightedData[locs, wts]`. Returns a `GeoGraphics` object;
/// `PlotLegends -> Automatic` adds a color-scale legend.
pub fn geo_histogram_ast(args: &[Expr]) -> Result<Expr, InterpreterError> {
  let unevaluated = || {
    Ok(Expr::FunctionCall {
      name: "GeoHistogram".to_string(),
      args: args.to_vec().into(),
    })
  };
  if args.is_empty() {
    return unevaluated();
  }
  let data = crate::evaluator::evaluate_expr_to_expr(&args[0])?;
  let (pts, wts) = histogram_locations(&data);
  if pts.is_empty() {
    return unevaluated();
  }

  // Positional arguments (bin spec, then height spec); Rules are options.
  let mut shape = BinShape::Hexagon;
  let mut size = BinSize::Across(12.0);
  let mut hspec = HeightSpec::Count;
  let mut legend = false;
  let mut opts: Vec<Expr> = Vec::new();
  for raw in &args[1..] {
    let arg = crate::evaluator::evaluate_expr_to_expr(raw)
      .unwrap_or_else(|_| raw.clone());
    if let Expr::Rule {
      pattern,
      replacement,
    } = &arg
    {
      if matches!(pattern.as_ref(), Expr::Identifier(n) if n == "PlotLegends") {
        // PlotLegends -> None keeps the default (no legend); anything else
        // (Automatic, Placed[…], …) turns the color-scale bar on.
        legend =
          !matches!(replacement.as_ref(), Expr::Identifier(s) if s == "None");
      } else {
        opts.push(arg.clone());
      }
    } else if let Some((sh, sz)) = parse_bin_spec(&arg) {
      if let Some(sh) = sh {
        shape = sh;
      }
      if let Some(sz) = sz {
        size = sz;
      }
    } else if let Some(hs) = parse_height_spec(&arg) {
      hspec = hs;
    }
  }

  let bins = compute_geo_bins(&pts, &wts, shape, &size);
  let total: f64 = bins.iter().map(|b| b.1).sum();
  let value = |ring: &[(f64, f64)], v: f64| match hspec {
    HeightSpec::Count => v,
    HeightSpec::Probability => {
      if total > 0.0 {
        v / total
      } else {
        0.0
      }
    }
    HeightSpec::Intensity => v / ring_area_deg2(ring).max(1e-12),
    HeightSpec::Pdf => v / (total.max(1e-12) * ring_area_deg2(ring).max(1e-12)),
  };
  let values: Vec<f64> = bins.iter().map(|(ring, v)| value(ring, *v)).collect();
  let vmax = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);

  // Shade each bin by its (max-normalized) value.
  let mut items: Vec<Expr> = Vec::with_capacity(bins.len() * 2);
  for ((ring, _), v) in bins.iter().zip(&values) {
    let t = if vmax > 0.0 { v / vmax } else { 1.0 };
    let (r, g, b) = heat_color(t);
    items.push(Expr::FunctionCall {
      name: "RGBColor".to_string(),
      args: vec![Expr::Real(r), Expr::Real(g), Expr::Real(b)].into(),
    });
    items.push(Expr::FunctionCall {
      name: "Woxi`GeoHistogramBin".to_string(),
      args: vec![Expr::List(
        ring
          .iter()
          .map(|(lat, lon)| {
            Expr::List(vec![Expr::Real(*lat), Expr::Real(*lon)].into())
          })
          .collect::<Vec<_>>()
          .into(),
      )]
      .into(),
    });
  }
  let content = Expr::List(items.into());
  let legend = legend.then_some(Legend {
    lo: 0.0,
    hi: vmax,
    color: heat_color,
  });
  let result = geographics_impl(&content, &opts, legend)?;
  // Keep the GeoGraphics head (`Head` reports GeoGraphics, as in the Wolfram
  // Language) while rendering as an ordinary SVG image.
  if let Expr::Graphics {
    svg, is_3d, source, ..
  } = &result
  {
    Ok(Expr::Graphics {
      svg: svg.clone(),
      is_3d: *is_3d,
      source: source.clone(),
      head: Some("GeoGraphics".to_string()),
    })
  } else {
    Ok(result)
  }
}

// ── Entry point ───────────────────────────────────────────────────────────

/// `GeoGraphics[content, opts…]` → a rendered world map as `Expr::Graphics`.
pub fn geographics_ast(args: &[Expr]) -> Result<Expr, InterpreterError> {
  let content = if args.is_empty() {
    Expr::List(vec![].into())
  } else {
    crate::evaluator::evaluate_expr_to_expr(&args[0])?
  };
  // `GeoGraphics` keeps its own symbolic head (so `Head` reports `GeoGraphics`,
  // matching wolframscript) while still rendering as an ordinary SVG image.
  let result = geographics_impl(&content, &args[1..], None)?;
  if let Expr::Graphics {
    svg, is_3d, source, ..
  } = &result
  {
    Ok(Expr::Graphics {
      svg: svg.clone(),
      is_3d: *is_3d,
      source: source.clone(),
      head: Some("GeoGraphics".to_string()),
    })
  } else {
    Ok(result)
  }
}

/// Render already-evaluated `content` with the given option arguments, plus an
/// optional color-scale legend (used by `GeoRegionValuePlot`).
fn geographics_impl(
  content: &Expr,
  opt_args: &[Expr],
  legend: Option<Legend>,
) -> Result<Expr, InterpreterError> {
  // Options: ImageSize (width), GeoRange, GeoProjection, GeoGridLines.
  let mut width = 360.0_f64;
  let mut range = GeoRange::Auto;
  let mut projection = Projection::EquidistantCylindrical;
  let mut gridlines = false;
  for raw in opt_args {
    let opt = crate::evaluator::evaluate_expr_to_expr(raw)
      .unwrap_or_else(|_| raw.clone());
    if let Expr::Rule {
      pattern,
      replacement,
    } = &opt
      && let Expr::Identifier(name) = pattern.as_ref()
    {
      match name.as_str() {
        "ImageSize" => {
          if let Some(w) = expr_to_f64(replacement) {
            if w > 0.0 {
              width = w;
            }
          } else if let Expr::List(items) = replacement.as_ref()
            && !items.is_empty()
            && let Some(w) = expr_to_f64(&items[0])
            && w > 0.0
          {
            width = w;
          }
        }
        "GeoRange" => {
          if let Some(r) = parse_geo_range(replacement) {
            range = r;
          }
        }
        "GeoProjection" => {
          if let Some(p) = parse_projection(replacement) {
            projection = p;
          }
        }
        "GeoGridLines" => {
          // Automatic/True turns the graticule on; None/False leaves it off.
          gridlines = matches!(
            replacement.as_ref(),
            Expr::Identifier(s) if s == "Automatic" || s == "True"
          );
        }
        _ => {}
      }
    }
  }

  // Auto-zoom: fit the view to the data positions (or the whole globe when
  // there are none). The image height follows the data aspect ratio.
  let mut positions = Vec::new();
  collect_positions(content, &mut positions);
  let proj = build_view(&positions, width, &range, projection);
  let height = proj.h;

  // Reserve a strip on the right for the color-scale legend when present.
  const LEGEND_WIDTH: f64 = 78.0;
  let canvas_w = if legend.is_some() {
    width + LEGEND_WIDTH
  } else {
    width
  };

  let mut svg = String::with_capacity(64 * 1024);
  svg.push_str(&format!(
    "<svg width=\"{canvas_w:.0}\" height=\"{height:.0}\" \
     viewBox=\"0 0 {canvas_w:.0} {height:.0}\" \
     preserveAspectRatio=\"xMidYMid meet\" \
     xmlns=\"http://www.w3.org/2000/svg\">\n"
  ));

  // Clip all map drawing to the map box so nothing (overflowing coastlines,
  // primitives, country fills) spills into the margin or the legend strip.
  svg.push_str(&format!(
    "<defs><clipPath id=\"geomap\"><rect x=\"0\" y=\"0\" \
     width=\"{width:.0}\" height=\"{height:.0}\"/></clipPath></defs>\n\
     <g clip-path=\"url(#geomap)\">\n"
  ));

  // Ocean background.
  svg.push_str(&format!(
    "<rect width=\"{width:.0}\" height=\"{height:.0}\" fill=\"{OCEAN_FILL}\"/>\n"
  ));

  // Landmasses with country borders (even-odd fill handles lakes/holes).
  for poly in world_polygons() {
    let mut d = String::new();
    for ring in poly {
      for (k, (lon, lat)) in ring.iter().enumerate() {
        let (x, y) = proj.project(*lon as f64, *lat as f64);
        if k == 0 {
          d.push_str(&format!("M {x:.1} {y:.1} "));
        } else {
          d.push_str(&format!("L {x:.1} {y:.1} "));
        }
      }
      d.push_str("Z ");
    }
    svg.push_str(&format!(
      "<path d=\"{d}\" fill=\"{LAND_FILL}\" fill-rule=\"evenodd\" \
       stroke=\"{BORDER_STROKE}\" stroke-width=\"0.4\"/>\n"
    ));
  }

  // Optional graticule (latitude/longitude grid lines).
  if gridlines {
    render_graticule(&mut svg, &proj);
  }

  // Foreground primitives (markers, points).
  let mut style = GeoStyle {
    color: Color::new(0.85, 0.18, 0.16),
    point_size: None,
  };
  render_content(content, &mut style, &proj, &mut svg);

  // End of clipped map content.
  svg.push_str("</g>\n");

  // Map frame, drawn on top of (and exactly around) the clipped map box.
  svg.push_str(&format!(
    "<rect x=\"0.5\" y=\"0.5\" width=\"{:.1}\" height=\"{:.1}\" fill=\"none\" \
     stroke=\"rgb(150,150,150)\" stroke-width=\"1\"/>\n",
    width - 1.0,
    height - 1.0
  ));

  // Color-scale legend (GeoRegionValuePlot).
  if let Some(leg) = legend {
    render_legend(&mut svg, &leg, width, height);
  }

  svg.push_str("</svg>");

  Ok(crate::graphics_result(svg))
}

/// Draw a vertical color-scale legend bar (high at top, low at bottom) in the
/// strip to the right of the map at `x = map_width`.
fn render_legend(svg: &mut String, leg: &Legend, map_width: f64, height: f64) {
  let bar_x = map_width + 14.0;
  let bar_w = 16.0;
  let top = 18.0_f64.min(height * 0.12);
  let bot = (height - 18.0).max(top + 1.0);
  let bar_h = bot - top;
  // Gradient fill, sampled as horizontal slices (no <defs> needed).
  let slices = 64;
  for i in 0..slices {
    // t = 1 at the top slice, 0 at the bottom.
    let t = 1.0 - (i as f64 + 0.5) / slices as f64;
    let (r, g, b) = (leg.color)(t);
    let (rr, gg, bb) = (
      (r * 255.0).round() as u8,
      (g * 255.0).round() as u8,
      (b * 255.0).round() as u8,
    );
    let y = top + bar_h * i as f64 / slices as f64;
    let sh = bar_h / slices as f64 + 0.6;
    svg.push_str(&format!(
      "<rect x=\"{bar_x:.1}\" y=\"{y:.2}\" width=\"{bar_w:.1}\" \
       height=\"{sh:.2}\" fill=\"rgb({rr},{gg},{bb})\"/>\n"
    ));
  }
  // Border around the bar.
  svg.push_str(&format!(
    "<rect x=\"{bar_x:.1}\" y=\"{top:.1}\" width=\"{bar_w:.1}\" \
     height=\"{bar_h:.1}\" fill=\"none\" stroke=\"rgb(120,120,120)\" \
     stroke-width=\"0.6\"/>\n"
  ));
  // Tick labels at min, midpoint and max.
  let label_x = bar_x + bar_w + 5.0;
  for (frac, value) in
    [(0.0, leg.hi), (0.5, (leg.lo + leg.hi) / 2.0), (1.0, leg.lo)]
  {
    let y = top + bar_h * frac + 3.5;
    svg.push_str(&format!(
      "<text x=\"{label_x:.1}\" y=\"{y:.1}\" font-family=\"sans-serif\" \
       font-size=\"11\" fill=\"rgb(60,60,60)\">{}</text>\n",
      format_legend_value(value)
    ));
  }
}

#[cfg(test)]
mod entity_resolution_tests {
  use super::*;

  fn city(parts: &[&str]) -> Expr {
    Expr::FunctionCall {
      name: "Entity".into(),
      args: vec![
        Expr::String("City".into()),
        Expr::List(
          parts
            .iter()
            .map(|p| Expr::String((*p).into()))
            .collect::<Vec<_>>()
            .into(),
        ),
      ]
      .into(),
    }
  }

  #[test]
  fn city_entity_resolves_to_subdivision_centroid() {
    // keshvar has no city coordinates, so Munich resolves to the center of its
    // administrative subdivision, Bavaria (Bayern, DE-BY).
    let (lat, lon) =
      entity_to_latlon(&city(&["Munich", "Bavaria", "Germany"])).unwrap();
    assert!((lat - 48.7904472).abs() < 1e-3, "lat {lat}");
    assert!((lon - 11.4978895).abs() < 1e-3, "lon {lon}");
  }

  #[test]
  fn region_matches_name_translation_and_code() {
    // The English name, the local name and the ISO 3166-2 code all match.
    let de = keshvar_country("Germany").unwrap();
    let by = subdivision_centroid_in(&de, "Bavaria").unwrap();
    assert_eq!(subdivision_centroid_in(&de, "Bayern"), Some(by));
    assert_eq!(subdivision_centroid_in(&de, "by"), Some(by));
  }

  #[test]
  fn unknown_region_falls_back_to_country_centroid() {
    // A city whose region can't be matched still resolves to the country center.
    let (lat, lon) =
      entity_to_latlon(&city(&["Nowhere", "Atlantis", "Germany"])).unwrap();
    assert!((lat - 51.165691).abs() < 1e-3, "lat {lat}");
    assert!((lon - 10.451526).abs() < 1e-3, "lon {lon}");
  }

  #[test]
  fn country_entity_resolves_to_country_centroid() {
    let e = Expr::FunctionCall {
      name: "Entity".into(),
      args: vec![
        Expr::String("Country".into()),
        Expr::String("France".into()),
      ]
      .into(),
    };
    let (lat, lon) = entity_to_latlon(&e).unwrap();
    assert!((lat - 46.227638).abs() < 1e-2, "lat {lat}");
    assert!((lon - 2.213749).abs() < 1e-2, "lon {lon}");
  }
}

/// Format a legend tick value compactly (drop a redundant trailing `.0`).
fn format_legend_value(v: f64) -> String {
  if v.fract() == 0.0 && v.abs() < 1e15 {
    format!("{}", v as i64)
  } else {
    let s = format!("{v:.2}");
    s.trim_end_matches('0').trim_end_matches('.').to_string()
  }
}
