//! `GeoGraphics` — minimal geographic map rendering.
//!
//! Renders a whole-world equirectangular map using the embedded
//! lowest-resolution (1:110m) Natural Earth admin-0 countries data set
//! (see `resources/ne_110m_countries.bin`, generated by
//! `scripts/gen_geo_data.wls` from <https://www.naturalearthdata.com>).
//!
//! Supported geo primitives inside the content list:
//!   * `GeoMarker[pos]` / `GeoMarker[{pos, …}]` — a map pin at each position
//!   * `Point[pos]` / `Point[{pos, …}]`         — a filled dot at each position
//! plus the color directives and `PointSize` understood by ordinary Graphics.
//!
//! A position is `GeoPosition[{lat, lon}]`, `GeoPosition[{lat, lon, h}]` or a
//! bare `{lat, lon}` pair (latitude first, matching the Wolfram Language).
//!
//! The view auto-zooms to fit the data: a single point gets a square regional
//! window, several points are framed with padding, and a map with no data shows
//! the whole globe. The image height follows the data aspect ratio so the map
//! is never distorted. `ImageSize` (width) and `GeoRange` (`"World"`, `All`, or
//! an explicit `{{latmin, latmax}, {lonmin, lonmax}}` window) are honored.

use crate::InterpreterError;
use crate::functions::graphics::{Color, expr_to_f64, parse_color};
use crate::syntax::Expr;
use std::sync::OnceLock;

/// Embedded Natural Earth 1:110m countries blob. See module docs / generator.
static COUNTRIES_BIN: &[u8] =
  include_bytes!("../../resources/ne_110m_countries.bin");

/// A polygon is a list of rings; each ring is a list of (lon, lat) degrees.
type Ring = Vec<(f32, f32)>;
type Polygon = Vec<Ring>;

fn read_u32(buf: &[u8], i: &mut usize) -> u32 {
  let v = u32::from_le_bytes([buf[*i], buf[*i + 1], buf[*i + 2], buf[*i + 3]]);
  *i += 4;
  v
}

fn read_u16(buf: &[u8], i: &mut usize) -> u16 {
  let v = u16::from_le_bytes([buf[*i], buf[*i + 1]]);
  *i += 2;
  v
}

fn read_i16(buf: &[u8], i: &mut usize) -> i16 {
  let v = i16::from_le_bytes([buf[*i], buf[*i + 1]]);
  *i += 2;
  v
}

fn decode_polygons(buf: &[u8]) -> Vec<Polygon> {
  let mut i = 0usize;
  let num_polys = read_u32(buf, &mut i) as usize;
  let mut polys = Vec::with_capacity(num_polys);
  for _ in 0..num_polys {
    let num_rings = read_u16(buf, &mut i) as usize;
    let mut rings = Vec::with_capacity(num_rings);
    for _ in 0..num_rings {
      let n = read_u16(buf, &mut i) as usize;
      let mut ring = Vec::with_capacity(n);
      for _ in 0..n {
        let lon = read_i16(buf, &mut i) as f32 / 100.0;
        let lat = read_i16(buf, &mut i) as f32 / 100.0;
        ring.push((lon, lat));
      }
      rings.push(ring);
    }
    polys.push(rings);
  }
  polys
}

fn world_polygons() -> &'static Vec<Polygon> {
  static CACHE: OnceLock<Vec<Polygon>> = OnceLock::new();
  CACHE.get_or_init(|| decode_polygons(COUNTRIES_BIN))
}

// ── Cartographic colors (light "Default"-style basemap) ───────────────────

const OCEAN_FILL: &str = "rgb(214,232,245)";
const LAND_FILL: &str = "rgb(245,242,233)";
const BORDER_STROKE: &str = "rgb(176,169,159)";

// ── Position extraction ───────────────────────────────────────────────────

/// Extract `(lat, lon)` from `GeoPosition[{lat, lon[, h]}]` or a bare
/// `{lat, lon[, h]}` list.
fn position_to_latlon(expr: &Expr) -> Option<(f64, f64)> {
  let coords = match expr {
    Expr::FunctionCall { name, args }
      if name == "GeoPosition" && args.len() == 1 =>
    {
      &args[0]
    }
    other => other,
  };
  if let Expr::List(items) = coords
    && items.len() >= 2
  {
    let lat = expr_to_f64(&items[0])?;
    let lon = expr_to_f64(&items[1])?;
    return Some((lat, lon));
  }
  None
}

/// Extract one or more positions from a `GeoMarker`/`Point` argument, which may
/// be a single position or a list of positions.
fn positions_from_arg(expr: &Expr) -> Vec<(f64, f64)> {
  // Single position forms first.
  if let Some(p) = position_to_latlon(expr) {
    return vec![p];
  }
  // GeoPosition[{{lat,lon},{lat,lon},…}] or a bare list of positions.
  let list = match expr {
    Expr::FunctionCall { name, args }
      if name == "GeoPosition" && args.len() == 1 =>
    {
      &args[0]
    }
    other => other,
  };
  if let Expr::List(items) = list {
    let mut out = Vec::new();
    for it in items.iter() {
      if let Some(p) = position_to_latlon(it) {
        out.push(p);
      }
    }
    return out;
  }
  Vec::new()
}

// ── Projection / view window ──────────────────────────────────────────────

/// Padding added on each side of the data bounding box (fraction of span).
const RANGE_PADDING: f64 = 0.15;
/// Minimum half-span (in latitude degrees) when fitting two or more points,
/// so nearly-coincident points don't zoom past the basemap's resolution.
const MIN_HALFSPAN_LAT: f64 = 5.0;
/// Half-span (in latitude degrees) used for a single data point, giving it some
/// regional context.
const SINGLE_HALFSPAN_LAT: f64 = 12.0;

/// Equidistant-cylindrical projection with a standard parallel at the view
/// center latitude (longitudes are scaled by `cos(lat_c)` so the map is not
/// horizontally distorted around the center). For a whole-world view the center
/// latitude is 0, so this reduces to plain equirectangular.
struct GeoView {
  w: f64,
  h: f64,
  lon_c: f64,
  lat_c: f64,
  /// cos(standard parallel) — the longitude scale factor.
  k: f64,
  /// Pixels per projected degree (uniform in x and y).
  scale: f64,
}

impl GeoView {
  /// Project (lon, lat) in degrees to SVG pixel coordinates.
  fn project(&self, lon: f64, lat: f64) -> (f64, f64) {
    let px = self.w / 2.0 + (lon - self.lon_c) * self.k * self.scale;
    let py = self.h / 2.0 - (lat - self.lat_c) * self.scale;
    (px, py)
  }
}

/// Requested geographic range (the `GeoRange` option).
enum GeoRange {
  /// Fit the data automatically (the default).
  Auto,
  /// The whole globe.
  World,
  /// An explicit `{{latmin, latmax}, {lonmin, lonmax}}` window.
  Explicit {
    lat0: f64,
    lat1: f64,
    lon0: f64,
    lon1: f64,
  },
}

fn parse_geo_range(expr: &Expr) -> Option<GeoRange> {
  match expr {
    Expr::String(s) | Expr::Identifier(s) => match s.as_str() {
      "World" => Some(GeoRange::World),
      "All" | "Automatic" => Some(GeoRange::Auto),
      _ => None,
    },
    Expr::List(items) if items.len() == 2 => {
      if let (Expr::List(la), Expr::List(lo)) = (&items[0], &items[1])
        && la.len() == 2
        && lo.len() == 2
      {
        Some(GeoRange::Explicit {
          lat0: expr_to_f64(&la[0])?,
          lat1: expr_to_f64(&la[1])?,
          lon0: expr_to_f64(&lo[0])?,
          lon1: expr_to_f64(&lo[1])?,
        })
      } else {
        None
      }
    }
    _ => None,
  }
}

/// cos of a latitude, clamped so near-polar views don't blow up the x-scale.
fn lon_scale(lat_deg: f64) -> f64 {
  (lat_deg.clamp(-80.0, 80.0)).to_radians().cos().max(0.17)
}

/// Compute the view center and half-spans (in degrees) from the data positions
/// and the requested `GeoRange`. Returns `(lon_c, lat_c, half_lon, half_lat)`.
fn compute_window(
  positions: &[(f64, f64)],
  range: &GeoRange,
) -> (f64, f64, f64, f64) {
  match range {
    GeoRange::World => (0.0, 0.0, 180.0, 90.0),
    GeoRange::Explicit {
      lat0,
      lat1,
      lon0,
      lon1,
    } => (
      (lon0 + lon1) / 2.0,
      (lat0 + lat1) / 2.0,
      (lon1 - lon0).abs() / 2.0,
      (lat1 - lat0).abs() / 2.0,
    ),
    GeoRange::Auto => {
      if positions.is_empty() {
        return (0.0, 0.0, 180.0, 90.0);
      }
      let lat_min = positions.iter().map(|p| p.0).fold(f64::INFINITY, f64::min);
      let lat_max = positions
        .iter()
        .map(|p| p.0)
        .fold(f64::NEG_INFINITY, f64::max);
      let lon_min = positions.iter().map(|p| p.1).fold(f64::INFINITY, f64::min);
      let lon_max = positions
        .iter()
        .map(|p| p.1)
        .fold(f64::NEG_INFINITY, f64::max);
      let lat_c = (lat_min + lat_max) / 2.0;
      let lon_c = (lon_min + lon_max) / 2.0;
      let k = lon_scale(lat_c);

      let span_lat = lat_max - lat_min;
      let span_lon = lon_max - lon_min;
      if span_lat <= 0.0 && span_lon <= 0.0 {
        // Single point (or all coincident): a square regional window.
        return (lon_c, lat_c, SINGLE_HALFSPAN_LAT / k, SINGLE_HALFSPAN_LAT);
      }
      // Fit the bounding box, enforce a minimum span, then pad.
      let mut half_lat = (span_lat / 2.0).max(MIN_HALFSPAN_LAT);
      let mut half_lon = (span_lon / 2.0).max(MIN_HALFSPAN_LAT / k);
      half_lat *= 1.0 + RANGE_PADDING;
      half_lon *= 1.0 + RANGE_PADDING;
      (lon_c, lat_c, half_lon, half_lat)
    }
  }
}

/// Build the projection for the given data, image width and requested range.
/// The image height is derived from the (projected) data aspect ratio so the
/// map is never distorted.
fn build_view(
  positions: &[(f64, f64)],
  width: f64,
  range: &GeoRange,
) -> GeoView {
  let (lon_c, lat_c, half_lon, half_lat) = compute_window(positions, range);
  let k = lon_scale(lat_c);
  // Projected half-spans (degrees).
  let hx = (half_lon * k).max(1e-6);
  let hy = half_lat.max(1e-6);
  let height = (width * hy / hx).round().max(1.0);
  let scale = width / (2.0 * hx);
  GeoView {
    w: width,
    h: height,
    lon_c,
    lat_c,
    k,
    scale,
  }
}

// ── Marker rendering ──────────────────────────────────────────────────────

/// Append a teardrop map pin whose tip points at (px, py).
fn render_pin(svg: &mut String, px: f64, py: f64, color: &Color, scale: f64) {
  let r = 4.0 * scale;
  let d = 14.0 * scale; // tip-to-bulb-center distance
  let cy = py - d; // bulb center
  // Tangent points from the tip onto the bulb circle.
  let cos_t = (r / d).clamp(-1.0, 1.0);
  let sin_t = (1.0 - cos_t * cos_t).sqrt();
  let lx = px - r * sin_t;
  let rx = px + r * sin_t;
  let ty = cy + r * cos_t;
  let fill = color.to_svg_rgb();
  svg.push_str(&format!(
    "<path d=\"M {px:.1} {py:.1} L {rx:.1} {ty:.1} A {r:.1} {r:.1} 0 1 0 {lx:.1} {ty:.1} Z\" \
     fill=\"{fill}\" stroke=\"rgb(60,60,60)\" stroke-width=\"0.8\"/>\n"
  ));
  // White hole in the bulb.
  svg.push_str(&format!(
    "<circle cx=\"{px:.1}\" cy=\"{cy:.1}\" r=\"{:.1}\" fill=\"white\"/>\n",
    r * 0.45
  ));
}

/// Append a filled dot at (px, py).
fn render_dot(svg: &mut String, px: f64, py: f64, color: &Color, radius: f64) {
  svg.push_str(&format!(
    "<circle cx=\"{px:.1}\" cy=\"{py:.1}\" r=\"{radius:.1}\" fill=\"{}\"/>\n",
    color.to_svg_rgb()
  ));
}

// ── PointSize handling ────────────────────────────────────────────────────

/// Pixel radius for a dot given the current `PointSize` directive and image
/// width. Named sizes follow the usual Graphics conventions; numeric values are
/// fractions of the image width.
fn point_radius(point_size: &Option<Expr>, width: f64) -> f64 {
  match point_size {
    None => 3.0,
    Some(Expr::Identifier(s)) => match s.as_str() {
      "Tiny" => 1.5,
      "Small" => 2.5,
      "Medium" => 4.0,
      "Large" => 6.0,
      _ => 3.0,
    },
    Some(e) => match expr_to_f64(e) {
      Some(frac) if frac > 0.0 => (frac * width).max(1.0),
      _ => 3.0,
    },
  }
}

/// Pin scale factor for the current `PointSize` directive (the pin keeps a
/// recognizable shape, so `PointSize` only nudges its overall size).
fn pin_scale(point_size: &Option<Expr>) -> f64 {
  match point_size {
    Some(Expr::Identifier(s)) => match s.as_str() {
      "Tiny" => 0.7,
      "Small" => 0.85,
      "Large" => 1.25,
      _ => 1.0,
    },
    _ => 1.0,
  }
}

// ── Content walking ───────────────────────────────────────────────────────

struct GeoStyle {
  color: Color,
  point_size: Option<Expr>,
}

/// Collect every data position (from `GeoMarker`/`Point`) in the content tree,
/// used to compute the auto-zoom window.
fn collect_positions(expr: &Expr, out: &mut Vec<(f64, f64)>) {
  match expr {
    Expr::List(items) => {
      for it in items.iter() {
        collect_positions(it, out);
      }
    }
    Expr::FunctionCall { name, args } => match name.as_str() {
      "Directive" => {
        for a in args.iter() {
          collect_positions(a, out);
        }
      }
      "GeoMarker" | "Point" if !args.is_empty() => {
        out.extend(positions_from_arg(&args[0]));
      }
      _ => {}
    },
    _ => {}
  }
}

/// Walk the content list, tracking color/PointSize directives and emitting SVG
/// for each geo primitive encountered.
fn render_content(
  expr: &Expr,
  style: &mut GeoStyle,
  proj: &GeoView,
  svg: &mut String,
) {
  match expr {
    Expr::List(items) => {
      for it in items.iter() {
        render_content(it, style, proj, svg);
      }
    }
    Expr::FunctionCall { name, args } => match name.as_str() {
      "Directive" => {
        for a in args.iter() {
          render_content(a, style, proj, svg);
        }
      }
      "PointSize" | "AbsolutePointSize" if args.len() == 1 => {
        style.point_size = Some(args[0].clone());
      }
      "GeoMarker" if !args.is_empty() => {
        let scale = pin_scale(&style.point_size);
        for (lat, lon) in positions_from_arg(&args[0]) {
          let (px, py) = proj.project(lon, lat);
          render_pin(svg, px, py, &style.color, scale);
        }
      }
      "Point" if !args.is_empty() => {
        let radius = point_radius(&style.point_size, proj.w);
        for (lat, lon) in positions_from_arg(&args[0]) {
          let (px, py) = proj.project(lon, lat);
          render_dot(svg, px, py, &style.color, radius);
        }
      }
      _ => {
        // Treat anything color-like as a directive; ignore the rest.
        if let Some(c) = parse_color(expr) {
          style.color = c;
        }
      }
    },
    Expr::Identifier(_) => {
      if let Some(c) = parse_color(expr) {
        style.color = c;
      }
    }
    _ => {}
  }
}

// ── Entry point ───────────────────────────────────────────────────────────

/// `GeoGraphics[content, opts…]` → a rendered world map as `Expr::Graphics`.
pub fn geographics_ast(args: &[Expr]) -> Result<Expr, InterpreterError> {
  let content = if args.is_empty() {
    Expr::List(vec![].into())
  } else {
    crate::evaluator::evaluate_expr_to_expr(&args[0])?
  };

  // Options: ImageSize (width) and GeoRange.
  let mut width = 360.0_f64;
  let mut range = GeoRange::Auto;
  for raw in &args[1..] {
    let opt = crate::evaluator::evaluate_expr_to_expr(raw)
      .unwrap_or_else(|_| raw.clone());
    if let Expr::Rule {
      pattern,
      replacement,
    } = &opt
      && let Expr::Identifier(name) = pattern.as_ref()
    {
      match name.as_str() {
        "ImageSize" => {
          if let Some(w) = expr_to_f64(replacement) {
            if w > 0.0 {
              width = w;
            }
          } else if let Expr::List(items) = replacement.as_ref()
            && !items.is_empty()
            && let Some(w) = expr_to_f64(&items[0])
            && w > 0.0
          {
            width = w;
          }
        }
        "GeoRange" => {
          if let Some(r) = parse_geo_range(replacement) {
            range = r;
          }
        }
        _ => {}
      }
    }
  }

  // Auto-zoom: fit the view to the data positions (or the whole globe when
  // there are none). The image height follows the data aspect ratio.
  let mut positions = Vec::new();
  collect_positions(&content, &mut positions);
  let proj = build_view(&positions, width, &range);
  let height = proj.h;

  let mut svg = String::with_capacity(64 * 1024);
  svg.push_str(&format!(
    "<svg width=\"{width:.0}\" height=\"{height:.0}\" \
     viewBox=\"0 0 {width:.0} {height:.0}\" \
     preserveAspectRatio=\"xMidYMid meet\" \
     xmlns=\"http://www.w3.org/2000/svg\">\n"
  ));

  // Ocean background.
  svg.push_str(&format!(
    "<rect width=\"{width:.0}\" height=\"{height:.0}\" fill=\"{OCEAN_FILL}\"/>\n"
  ));

  // Landmasses with country borders (even-odd fill handles lakes/holes).
  for poly in world_polygons() {
    let mut d = String::new();
    for ring in poly {
      for (k, (lon, lat)) in ring.iter().enumerate() {
        let (x, y) = proj.project(*lon as f64, *lat as f64);
        if k == 0 {
          d.push_str(&format!("M {x:.1} {y:.1} "));
        } else {
          d.push_str(&format!("L {x:.1} {y:.1} "));
        }
      }
      d.push_str("Z ");
    }
    svg.push_str(&format!(
      "<path d=\"{d}\" fill=\"{LAND_FILL}\" fill-rule=\"evenodd\" \
       stroke=\"{BORDER_STROKE}\" stroke-width=\"0.4\"/>\n"
    ));
  }

  // Map frame.
  svg.push_str(&format!(
    "<rect x=\"0.5\" y=\"0.5\" width=\"{:.1}\" height=\"{:.1}\" fill=\"none\" \
     stroke=\"rgb(150,150,150)\" stroke-width=\"1\"/>\n",
    width - 1.0,
    height - 1.0
  ));

  // Foreground primitives (markers, points).
  let mut style = GeoStyle {
    color: Color::new(0.85, 0.18, 0.16),
    point_size: None,
  };
  render_content(&content, &mut style, &proj, &mut svg);

  svg.push_str("</svg>");

  Ok(crate::graphics_result(svg))
}
