// Functions are organized by categories
pub mod association_ast;
pub mod boolean_ast;
pub mod calculus;
pub mod calculus_ast;
pub mod cellular_automaton_ast;
pub mod control_flow_ast;
pub mod datetime_ast;
pub mod graphics;
pub mod graphicsbox;
pub mod linear_algebra_ast;
pub mod list_helpers_ast;
pub mod math_ast;
pub mod plot;
pub mod plot3d;
pub mod polynomial_ast;
pub mod predicate_ast;
pub mod quantity_ast;
pub mod scoping;
pub mod string_ast;

// Re-export all function implementations
pub use association_ast::*;
pub use boolean_ast::*;
pub use calculus::*;
pub use calculus_ast::*;
pub use cellular_automaton_ast::*;
pub use control_flow_ast::*;
pub use datetime_ast::*;
pub use graphics::*;
pub use linear_algebra_ast::*;
pub use list_helpers_ast::*;
pub use math_ast::*;
pub use plot::*;
pub use polynomial_ast::*;
pub use predicate_ast::*;
pub use quantity_ast::*;
pub use scoping::*;
pub use string_ast::*;
