"""Type stubs for the compiled extension module woxi._woxi."""

__version__: str

class WolframError(Exception):
    """Raised when Woxi fails to parse or evaluate Wolfram Language code."""

class Sound:
    base64: str
    mime: str
    label: str | None

class EvaluationResult:
    result: str
    stdout: str
    graphics: str | None
    svg: str | None
    sound: Sound | None
    warnings: list[str]

def interpret(code: str) -> str: ...
def evaluate(code: str, *, print_to_stdout: bool = False) -> EvaluationResult: ...
def clear_state() -> None: ...
def seed_rng(seed: int) -> None: ...
def unseed_rng() -> None: ...
def set_repl_mode(enabled: bool) -> None: ...
def set_messages_to_stdout(enabled: bool) -> None: ...
def set_system_variable(name: str, value: str) -> None: ...
def set_script_command_line(args: list[str]) -> None: ...
def take_error_trace() -> str | None: ...
